
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COLON COMMA FALSE FLOAT INTEGER LIST_BEGIN LIST_END NULL OBJECT_BEGIN OBJECT_END STRING TRUE\n        object : OBJECT_BEGIN OBJECT_END\n        \n        object : OBJECT_BEGIN tuples OBJECT_END\n        \n        tuples : tuple COMMA tuples\n        \n        tuples : tuple COMMA\n               | tuple\n        \n        tuple : STRING COLON element\n        \n        list : LIST_BEGIN LIST_END\n        \n        list : LIST_BEGIN commalist LIST_END\n        \n        commalist : element COMMA commalist\n        \n        commalist : element COMMA\n                  | element\n        \n        element : object\n                | list\n        \n        element : NULL\n        \n        element : TRUE\n        \n        element : FALSE\n        \n        element : FLOAT\n        \n        element : INTEGER\n        \n        element : STRING\n        '
    
_lr_action_items = {'OBJECT_BEGIN':([0,9,20,25,],[2,2,2,2,]),'$end':([1,3,7,],[0,-1,-2,]),'OBJECT_END':([2,3,4,5,7,8,10,11,12,13,14,15,16,17,18,19,21,24,],[3,-1,7,-5,-2,-4,-3,-19,-6,-12,-13,-14,-15,-16,-17,-18,-7,-8,]),'STRING':([2,8,9,20,25,],[6,6,11,11,11,]),'COMMA':([3,5,7,11,12,13,14,15,16,17,18,19,21,23,24,],[-1,8,-2,-19,-6,-12,-13,-14,-15,-16,-17,-18,-7,25,-8,]),'LIST_END':([3,7,11,13,14,15,16,17,18,19,20,21,22,23,24,25,26,],[-1,-2,-19,-12,-13,-14,-15,-16,-17,-18,21,-7,24,-11,-8,-10,-9,]),'COLON':([6,],[9,]),'NULL':([9,20,25,],[15,15,15,]),'TRUE':([9,20,25,],[16,16,16,]),'FALSE':([9,20,25,],[17,17,17,]),'FLOAT':([9,20,25,],[18,18,18,]),'INTEGER':([9,20,25,],[19,19,19,]),'LIST_BEGIN':([9,20,25,],[20,20,20,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'object':([0,9,20,25,],[1,13,13,13,]),'tuples':([2,8,],[4,10,]),'tuple':([2,8,],[5,5,]),'element':([9,20,25,],[12,23,23,]),'list':([9,20,25,],[14,14,14,]),'commalist':([20,25,],[22,26,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> object","S'",1,None,None,None),
  ('object -> OBJECT_BEGIN OBJECT_END','object',2,'p_object_empty','ExtendedJsonParser.py',148),
  ('object -> OBJECT_BEGIN tuples OBJECT_END','object',3,'p_object','ExtendedJsonParser.py',154),
  ('tuples -> tuple COMMA tuples','tuples',3,'p_tuples_tuple_comma_tuples','ExtendedJsonParser.py',164),
  ('tuples -> tuple COMMA','tuples',2,'p_tuples_tuple_comma_or_tuple','ExtendedJsonParser.py',171),
  ('tuples -> tuple','tuples',1,'p_tuples_tuple_comma_or_tuple','ExtendedJsonParser.py',172),
  ('tuple -> STRING COLON element','tuple',3,'p_tuple','ExtendedJsonParser.py',178),
  ('list -> LIST_BEGIN LIST_END','list',2,'p_list_empty','ExtendedJsonParser.py',191),
  ('list -> LIST_BEGIN commalist LIST_END','list',3,'p_list','ExtendedJsonParser.py',197),
  ('commalist -> element COMMA commalist','commalist',3,'p_commalist_element_comma_commalist','ExtendedJsonParser.py',207),
  ('commalist -> element COMMA','commalist',2,'p_commalist_element_comma_or_element','ExtendedJsonParser.py',217),
  ('commalist -> element','commalist',1,'p_commalist_element_comma_or_element','ExtendedJsonParser.py',218),
  ('element -> object','element',1,'p_element_object_or_list','ExtendedJsonParser.py',237),
  ('element -> list','element',1,'p_element_object_or_list','ExtendedJsonParser.py',238),
  ('element -> NULL','element',1,'p_element_NULL','ExtendedJsonParser.py',244),
  ('element -> TRUE','element',1,'p_element_TRUE','ExtendedJsonParser.py',250),
  ('element -> FALSE','element',1,'p_element_FALSE','ExtendedJsonParser.py',256),
  ('element -> FLOAT','element',1,'p_element_FLOAT','ExtendedJsonParser.py',262),
  ('element -> INTEGER','element',1,'p_element_INTEGER','ExtendedJsonParser.py',268),
  ('element -> STRING','element',1,'p_element_STRING','ExtendedJsonParser.py',274),
]
